[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "testgen"
version = "0.0.0"
description = "Test procedure generator."
requires-python = ">= 3.6" # Based on ReportLab's requirement.
dependencies = [
    "reportlab>=4.2.0",
]
