[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "testgen"
description = "Test procedure generator."
license = {file = "LICENSE.txt"}
dynamic = ["version"]

# This version number is automatically inserted into the user manual, however,
# the '>=' is not, so the manual language needs to be updated separately
# if the comparison operator changes.
requires-python = ">= 3.11"

dependencies = [
    "reportlab>=4.2.0",
]

classifiers = [
    "Environment :: Console",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Testing :: Acceptance",
    "Topic :: Text Processing :: Markup",
]


[tool.hatch.version]
path = "testgen/version.py"
