"""
This is a Sphinx extension to automatically generate the appendix listing
available ISO 7010 symbols.
"""

import os

import atform
import sphinx


# Output reStructuredText file.
RST_PATH = os.path.join("source", "iso7010.rst")


# Attributions for symbols not in the public domain.
ATTRIBUTION = {
    "M002": """
    Image by ISO licensed under
    `CC BY-SA 3.0 <https://creativecommons.org/licenses/by-sa/3.0/deed.en>`_
    """,
}


# Footnote content; automatically generated for attributions.
footnotes = []


# Path to the image files.
IMAGE_PATH = "/".join(("..", "..", "atform", "iso7010"))


# Width of the symbols in inches.
IMAGE_WIDTH = 0.5


# Indentation used for generated reST.
INDENT = " " * 4


def setup(app):
    """Extension entry point."""
    app.connect("config-inited", config_inited_handler)


def config_inited_handler(_app, _config):
    """config-inited event handler."""
    write_rst()
    # raise sphinx.errors.ExtensionError("stop here")


def write_rst():
    """Generates the reStructuredText output file."""
    symbols = atform.iso7010.SYMBOLS
    lines = []

    lines.append(
        f"""..
{INDENT}Do not modify this file.
{INDENT}This file is automatically generated by the iso7010 Sphinx extension.


.. _iso7010:

ISO 7010 Symbols
================
The following symbols are available for use with :py:func:`atform.notice`.
"""
    )

    lines.extend(image_sub(sym) for sym in symbols)
    lines.append(table())
    lines.extend(symbol_row(sym) for sym in sorted(symbols.keys()))
    lines.append("")
    lines.extend(gen_footnotes())
    with open(RST_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def image_sub(symbol):
    """Generates a substitution directive for a given image."""
    path = "/".join((IMAGE_PATH, f"{symbol}.svg"))
    return f"""
.. |{symbol}| image:: {path}
{INDENT}:width: {IMAGE_WIDTH} in
"""


def table():
    """Generates the table directive."""
    return f"""
.. tabularcolumns:: llp{{4in}}

.. csv-table::
{INDENT}:header: "Image", "Number", "Meaning"
{INDENT}:class: longtable"
"""


def symbol_row(symbol):
    """Generates a table row for a single symbol."""
    try:
        attribution = ATTRIBUTION[symbol]
    except KeyError:
        note = ""

    # Define a new footnote for the attribution.
    else:
        footnotes.append(attribution)
        note = f"[#f{len(footnotes)}]_"

    meaning = atform.iso7010.SYMBOLS[symbol]
    return f'{INDENT}"|{symbol}| {note}", "{symbol}", "{meaning}"'


def gen_footnotes():
    """Generates all footnotes."""
    lines = []
    lines.append(".. rubric:: Footnotes\n")
    for i, note in enumerate(footnotes, start=1):
        lines.append(f".. [#f{i}] {note}")
    return lines
