"""This module implements the API for defining embedded notices.

The process for handling embedded notices is as follows:

1. User creates a notice with notice().

2. The notice content is stored internally by its hash.

3. notice() returns a string containing the hash. The reason a string is
   returned is to simplify embedding notices in user-provided strings,
   such as procedure step text. The user can employ normal string operations
   to insert the notice where desired.

   Storing notices by their hash also supports GUI diff detection; any
   change to the notice will result in a different hash, which will
   alter the enclosing user-provided string, and be correctly detected as
   a difference.

4. Embedded hashes are extracted during the PDF build process and used
   to look up the stored notice content.
"""

import collections
import hashlib
import re

from . import error
from . import iso7010
from . import misc


# Internal storage object for each notice.
Notice = collections.namedtuple("Notice", ["symbol", "msg"])


# All defined notices keyed by hash.
notices = {}


# Pattern used to locate digests within user text, essentially searching for
# instances of strings generated by encode().
re_notice = re.compile(r"<atform\.notice:(?P<digest>[a-f\d]{32})>")


def calc_hash(notice_):
    """Computes the hash value of a notice tuple."""
    md5 = hashlib.md5()
    for field in notice_:
        md5.update(bytes(field, "utf-8"))
    return md5.hexdigest().lower()  # Ensure lower case for re_notice.


def encode(digest):
    """Creates a reference to a notice to be embedded in user content."""
    return f"<atform.notice:{digest}>"


def decode(s, mapping):
    """Finds notices embedded in user-provided content.

    The original content is separated into a list of strings and Notice
    tuples.
    """
    segments = []
    i = 0
    for match in re_notice.finditer(s):
        # Add any content before the digest.
        segments.append(s[i : match.start()])

        # Add note corresponding with the embedded digest.
        segments.append(mapping[match.group("digest")])

        i = match.end()

    segments.append(s[i:])  # Add remaining content after the final digest.

    # Remove empty strings resulting from notices at the beginning or end,
    # or multiple adjacent notices.
    return [s for s in segments if s]


################################################################################
# Public API
#
# Items in this area are documented and exported for use by end users.
################################################################################


@error.exit_on_script_error
def notice(symbol, message):
    """Creates an embedded notice, such as a warning.

    Embedded notices may be used in the following contexts:

    * Objective
    * Preconditions
    * Procedure step text

    Args:
        symbol (str): ISO 7010 number of the pictogram adjacent to the message.
            See user manual Appendix A for a list of supported symbols.
        message (str): Notice content; may contain multiple paragraphs
            and bullet lists created with :py:func:`atform.bullet_list`.

    Returns:
        str: A string to be inserted into surrouding text where the notice
        should appear. The returned string contains internal reference
        information and must not be modified.
    """
    try:
        iso7010.validate_ref(symbol)
    except TypeError as e:
        raise error.UserScriptError(
            f"Invalid symbol type: {type(symbol).__name__}",
            "Symbol must be a string.",
        ) from e
    except KeyError as e:
        raise error.UserScriptError(
            f'Undefined symbol: "{symbol}"',
            "See user manual Appendix A for a list of supported symbols.",
        ) from e
    notice_ = Notice(symbol, misc.nonempty_string("message", message))
    digest = calc_hash(notice_)
    notices[digest] = notice_
    return encode(digest)
